In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

## loading train data

In [2]:
df_train = pd.read_csv('train_data.csv',index_col='Id')
df_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## all the columns that is going to is in the output of this cell

In [3]:
df_train.replace({'MSZoning': {'C (all)':'C'}},inplace=True)
for col in df_train.columns:
    if col not in ['MSSubClass', 'LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                   '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageYrBlt', 'GarageArea', 'WoodDeckSF', 'EnclosedPorch', 'OpenPorchSF', 'LowQualFinSF',
                  '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'SalePrice', 'MoSold', 'YrSold']:
        tmp = df_train[col].tolist()
        tmp = set(tmp)
        obj1 = enumerate(tmp)
        tmp1 = list(obj1)
        tmp1[0]
        dic = {}
        for i in range(len(tmp1)):
            dic[tmp1[i][1]] = int(tmp1[i][0])
        print(f"this column is {col}")
        print(dic)
        print("-"*100)

this column is MSZoning
{'RL': 0, 'FV': 1, 'RH': 2, 'RM': 3, 'C': 4}
----------------------------------------------------------------------------------------------------
this column is Street
{'Pave': 0, 'Grvl': 1}
----------------------------------------------------------------------------------------------------
this column is Alley
{nan: 0, 'Grvl': 1, 'Pave': 2}
----------------------------------------------------------------------------------------------------
this column is LotShape
{'Reg': 0, 'IR3': 1, 'IR1': 2, 'IR2': 3}
----------------------------------------------------------------------------------------------------
this column is LandContour
{'Lvl': 0, 'HLS': 1, 'Bnk': 2, 'Low': 3}
----------------------------------------------------------------------------------------------------
this column is Utilities
{'NoSeWa': 0, 'AllPub': 1}
----------------------------------------------------------------------------------------------------
this column is LotConfig
{'CulDSac': 0, 'Corner': 1, 'FR2': 2, 'Inside': 3, 'FR3': 4}
----------------------------------------------------------------------------------------------------
this column is LandSlope
{'Mod': 0, 'Sev': 1, 'Gtl': 2}
----------------------------------------------------------------------------------------------------
this column is Neighborhood
{'Blmngtn': 0, 'BrkSide': 1, 'Crawfor': 2, 'ClearCr': 3, 'StoneBr': 4, 'Edwards': 5, 'NWAmes': 6, 'Sawyer': 7, 'OldTown': 8, 'Timber': 9, 'BrDale': 10, 'Somerst': 11, 'MeadowV': 12, 'SWISU': 13, 'Mitchel': 14, 'NoRidge': 15, 'Gilbert': 16, 'IDOTRR': 17, 'CollgCr': 18, 'NAmes': 19, 'Veenker': 20, 'NPkVill': 21, 'NridgHt': 22, 'SawyerW': 23, 'Blueste': 24}
----------------------------------------------------------------------------------------------------
this column is Condition1
{'PosN': 0, 'RRNn': 1, 'RRAe': 2, 'Artery': 3, 'RRNe': 4, 'RRAn': 5, 'PosA': 6, 'Norm': 7, 'Feedr': 8}
----------------------------------------------------------------------------------------------------
this column is Condition2
{'RRNn': 0, 'PosN': 1, 'RRAe': 2, 'Artery': 3, 'RRAn': 4, 'PosA': 5, 'Norm': 6, 'Feedr': 7}
----------------------------------------------------------------------------------------------------
this column is BldgType
{'2fmCon': 0, '1Fam': 1, 'TwnhsE': 2, 'Duplex': 3, 'Twnhs': 4}
----------------------------------------------------------------------------------------------------
this column is HouseStyle
{'2Story': 0, '1.5Unf': 1, '1.5Fin': 2, 'SLvl': 3, 'SFoyer': 4, '2.5Unf': 5, '1Story': 6, '2.5Fin': 7}
----------------------------------------------------------------------------------------------------
this column is OverallQual
{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9}
----------------------------------------------------------------------------------------------------
this column is OverallCond
{1: 0, 2: 1, 3: 2, 4: 3, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8}
----------------------------------------------------------------------------------------------------
this column is RoofStyle
{'Hip': 0, 'Flat': 1, 'Mansard': 2, 'Shed': 3, 'Gambrel': 4, 'Gable': 5}
----------------------------------------------------------------------------------------------------
this column is RoofMatl
{'Roll': 0, 'Metal': 1, 'ClyTile': 2, 'WdShake': 3, 'CompShg': 4, 'Tar&Grv': 5, 'Membran': 6, 'WdShngl': 7}
----------------------------------------------------------------------------------------------------
this column is Exterior1st
{'BrkFace': 0, 'CBlock': 1, 'BrkComm': 2, 'AsbShng': 3, 'Wd Sdng': 4, 'Stucco': 5, 'Stone': 6, 'MetalSd': 7, 'AsphShn': 8, 'ImStucc': 9, 'WdShing': 10, 'CemntBd': 11, 'Plywood': 12, 'HdBoard': 13, 'VinylSd': 14}
----------------------------------------------------------------------------------------------------
this column is Exterior2nd
{'BrkFace': 0, 'Other': 1, 'CBlock': 2, 'CmentBd': 3, 'Wd Sdng': 4, 'Stucco': 5, 'AsbShng': 6, 'Brk Cmn': 7, 'MetalSd': 8, 'AsphShn': 9, 'Stone': 10, 'ImStucc': 11, 'Wd Shng': 12, 'Plywood': 13, 'HdBoard': 14, 'VinylSd': 15}
----------------------------------------------------------------------------------------------------
this column is MasVnrType
{'BrkFace': 0, nan: 1, 'None': 2, 'BrkCmn': 3, 'Stone': 4}
----------------------------------------------------------------------------------------------------
this column is ExterQual
{'TA': 0, 'Gd': 1, 'Fa': 2, 'Ex': 3}
----------------------------------------------------------------------------------------------------
this column is ExterCond
{'Po': 0, 'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}
----------------------------------------------------------------------------------------------------
this column is Foundation
{'CBlock': 0, 'Slab': 1, 'Stone': 2, 'BrkTil': 3, 'Wood': 4, 'PConc': 5}
----------------------------------------------------------------------------------------------------
this column is BsmtQual
{nan: 0, 'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}
----------------------------------------------------------------------------------------------------
this column is BsmtCond
{nan: 0, 'Po': 1, 'Gd': 2, 'TA': 3, 'Fa': 4}
----------------------------------------------------------------------------------------------------
this column is BsmtExposure
{nan: 0, 'Gd': 1, 'No': 2, 'Mn': 3, 'Av': 4}
----------------------------------------------------------------------------------------------------
this column is BsmtFinType1
{nan: 0, 'Rec': 1, 'ALQ': 2, 'LwQ': 3, 'GLQ': 4, 'Unf': 5, 'BLQ': 6}
----------------------------------------------------------------------------------------------------
this column is BsmtFinType2
{nan: 0, 'BLQ': 1, 'ALQ': 2, 'LwQ': 3, 'GLQ': 4, 'Unf': 5, 'Rec': 6}
----------------------------------------------------------------------------------------------------
this column is Heating
{'OthW': 0, 'GasA': 1, 'GasW': 2, 'Floor': 3, 'Grav': 4, 'Wall': 5}
----------------------------------------------------------------------------------------------------
this column is HeatingQC
{'Po': 0, 'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}
----------------------------------------------------------------------------------------------------
this column is CentralAir
{'N': 0, 'Y': 1}
----------------------------------------------------------------------------------------------------
this column is Electrical
{nan: 0, 'FuseP': 1, 'FuseF': 2, 'FuseA': 3, 'Mix': 4, 'SBrkr': 5}
----------------------------------------------------------------------------------------------------
this column is BsmtFullBath
{0: 0, 1: 1, 2: 2, 3: 3}
----------------------------------------------------------------------------------------------------
this column is BsmtHalfBath
{0: 0, 1: 1, 2: 2}
----------------------------------------------------------------------------------------------------
this column is FullBath
{0: 0, 1: 1, 2: 2, 3: 3}
----------------------------------------------------------------------------------------------------
this column is HalfBath
{0: 0, 1: 1, 2: 2}
----------------------------------------------------------------------------------------------------
this column is BedroomAbvGr
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 8: 7}
----------------------------------------------------------------------------------------------------
this column is KitchenAbvGr
{0: 0, 1: 1, 2: 2, 3: 3}
----------------------------------------------------------------------------------------------------
this column is KitchenQual
{'TA': 0, 'Gd': 1, 'Fa': 2, 'Ex': 3}
----------------------------------------------------------------------------------------------------
this column is TotRmsAbvGrd
{2: 0, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: 7, 10: 8, 11: 9, 12: 10, 14: 11}
----------------------------------------------------------------------------------------------------
this column is Functional
{'Mod': 0, 'Maj1': 1, 'Min2': 2, 'Sev': 3, 'Min1': 4, 'Typ': 5, 'Maj2': 6}
----------------------------------------------------------------------------------------------------
this column is Fireplaces
{0: 0, 1: 1, 2: 2, 3: 3}
----------------------------------------------------------------------------------------------------
this column is FireplaceQu
{nan: 0, 'Po': 1, 'Gd': 2, 'TA': 3, 'Ex': 4, 'Fa': 5}
----------------------------------------------------------------------------------------------------
this column is GarageType
{nan: 0, 'CarPort': 1, '2Types': 2, 'BuiltIn': 3, 'Basment': 4, 'Attchd': 5, 'Detchd': 6}
----------------------------------------------------------------------------------------------------
this column is GarageFinish
{nan: 0, 'Fin': 1, 'Unf': 2, 'RFn': 3}
----------------------------------------------------------------------------------------------------
this column is GarageCars
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
----------------------------------------------------------------------------------------------------
this column is GarageQual
{nan: 0, 'Po': 1, 'Gd': 2, 'TA': 3, 'Ex': 4, 'Fa': 5}
----------------------------------------------------------------------------------------------------
this column is GarageCond
{nan: 0, 'Po': 1, 'Gd': 2, 'TA': 3, 'Ex': 4, 'Fa': 5}
----------------------------------------------------------------------------------------------------
this column is PavedDrive
{'N': 0, 'P': 1, 'Y': 2}
----------------------------------------------------------------------------------------------------
this column is PoolQC
{nan: 0, 'Gd': 1, 'Fa': 2, 'Ex': 3}
----------------------------------------------------------------------------------------------------
this column is Fence
{nan: 0, 'MnWw': 1, 'GdWo': 2, 'MnPrv': 3, 'GdPrv': 4}
----------------------------------------------------------------------------------------------------
this column is MiscFeature
{nan: 0, 'TenC': 1, 'Shed': 2, 'Gar2': 3, 'Othr': 4}
----------------------------------------------------------------------------------------------------
this column is SaleType
{'ConLD': 0, 'New': 1, 'ConLI': 2, 'WD': 3, 'COD': 4, 'ConLw': 5, 'Oth': 6, 'CWD': 7, 'Con': 8}
----------------------------------------------------------------------------------------------------
this column is SaleCondition
{'Normal': 0, 'Alloca': 1, 'Family': 2, 'Partial': 3, 'AdjLand': 4, 'Abnorml': 5}
----------------------------------------------------------------------------------------------------

## preprocess on train data

In [4]:
for col in df_train.columns:
    if col not in ['MSSubClass', 'LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                   '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageYrBlt', 'GarageArea', 'WoodDeckSF', 'EnclosedPorch', 'OpenPorchSF', 'LowQualFinSF',
                  '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'SalePrice', 'MoSold', 'YrSold']:
        tmp = df_train[col].tolist()
        tmp = set(tmp)
        obj1 = enumerate(tmp)
        tmp1 = list(obj1)
        tmp1[0]
        dic = {}
        for i in range(len(tmp1)):
            dic[tmp1[i][1]] = int(tmp1[i][0])
        df_train.replace({col: dic}, inplace=True)
df_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,0,65.0,8450,0,0,0,0,1,3,...,0,0,0,0,0,2,2008,3,0,208500
2,20,0,80.0,9600,0,0,0,0,1,2,...,0,0,0,0,0,5,2007,3,0,181500
3,60,0,68.0,11250,0,0,2,0,1,3,...,0,0,0,0,0,9,2008,3,0,223500
4,70,0,60.0,9550,0,0,2,0,1,1,...,0,0,0,0,0,2,2006,3,5,140000
5,60,0,84.0,14260,0,0,2,0,1,2,...,0,0,0,0,0,12,2008,3,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,0,62.0,7917,0,0,0,0,1,3,...,0,0,0,0,0,8,2007,3,0,175000
1457,20,0,85.0,13175,0,0,0,0,1,3,...,0,0,3,0,0,2,2010,3,0,210000
1458,70,0,66.0,9042,0,0,0,0,1,3,...,0,0,4,2,2500,5,2010,3,0,266500
1459,20,0,68.0,9717,0,0,0,0,1,3,...,0,0,0,0,0,4,2010,3,0,142125
1460,20,0,75.0,9937,0,0,0,0,1,3,...,0,0,0,0,0,6,2008,3,0,147500

## replace NaN with mean of column in train data

In [5]:
null_columns=df_train.columns[df_train.isnull().any()]
print(null_columns)
for i in null_columns:
    print(df_train[df_train[i].isnull()][null_columns])
for i in null_columns:
    df_train[i].fillna((df_train[i].mean()), inplace=True)
null_columns=df_train.columns[df_train.isnull().any()]
print(null_columns)

Index(['LotFrontage', 'MasVnrArea', 'GarageYrBlt'], dtype='object')
      LotFrontage  MasVnrArea  GarageYrBlt
Id
8             NaN       240.0       1973.0
13            NaN         0.0       1962.0
15            NaN       212.0       1960.0
17            NaN       180.0       1970.0
25            NaN         0.0       1968.0
...           ...         ...          ...
1430          NaN       310.0       1981.0
1432          NaN         0.0       1976.0
1442          NaN       147.0       2004.0
1444          NaN         0.0       1916.0
1447          NaN       189.0       1962.0

[259 rows x 3 columns]
      LotFrontage  MasVnrArea  GarageYrBlt
Id
235           NaN         NaN       2002.0
530           NaN         NaN       1975.0
651          65.0         NaN       2007.0
937          67.0         NaN       2003.0
974          95.0         NaN       2007.0
978          35.0         NaN       2007.0
1244        107.0         NaN       2006.0
1279         75.0         NaN       2002.0
      LotFrontage  MasVnrArea  GarageYrBlt
Id
40           65.0         0.0          NaN
49           33.0         0.0          NaN
79           72.0         0.0          NaN
89          105.0         0.0          NaN
90           60.0         0.0          NaN
...           ...         ...          ...
1350         50.0         0.0          NaN
1408          NaN         0.0          NaN
1450         21.0         0.0          NaN
1451         60.0         0.0          NaN
1454         90.0         0.0          NaN

[81 rows x 3 columns]
Index([], dtype='object')

## seperate sale price from train data

In [6]:
y = df_train['SalePrice'].copy()
df_train = df_train.drop(columns=['SalePrice'])
df_train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,0,65.0,8450,0,0,0,0,1,3,...,0,0,0,0,0,0,2,2008,3,0
2,20,0,80.0,9600,0,0,0,0,1,2,...,0,0,0,0,0,0,5,2007,3,0
3,60,0,68.0,11250,0,0,2,0,1,3,...,0,0,0,0,0,0,9,2008,3,0
4,70,0,60.0,9550,0,0,2,0,1,1,...,0,0,0,0,0,0,2,2006,3,5
5,60,0,84.0,14260,0,0,2,0,1,2,...,0,0,0,0,0,0,12,2008,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,0,62.0,7917,0,0,0,0,1,3,...,0,0,0,0,0,0,8,2007,3,0
1457,20,0,85.0,13175,0,0,0,0,1,3,...,0,0,0,3,0,0,2,2010,3,0
1458,70,0,66.0,9042,0,0,0,0,1,3,...,0,0,0,4,2,2500,5,2010,3,0
1459,20,0,68.0,9717,0,0,0,0,1,3,...,0,0,0,0,0,0,4,2010,3,0
1460,20,0,75.0,9937,0,0,0,0,1,3,...,0,0,0,0,0,0,6,2008,3,0

## we can't normalize y because "TweedieRegressor(power=2, alpha=0.5, link='log')" only gets [0,+inf)

In [7]:
# range_y = y.max() - y.min()
# mean_y = y.mean()
# y = (y - mean_y) / range_y
# y.head()

Id
1    0.038299
2    0.000804
3    0.059129
4   -0.056827
5    0.095929
Name: SalePrice, dtype: float64

## delete columns with more than 0.75 correlation to reduce number of unnecessary features

In [7]:
corr_matrix = df_train.corr()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))
to_drop_train = [column for column in upper.columns if any(upper[column] > 0.75)]
print(to_drop_train)
df_train = df_train.drop(df_train[to_drop_train], axis=1)
df_train

['Exterior2nd', '1stFlrSF', 'TotRmsAbvGrd', 'FireplaceQu', 'GarageYrBlt', 'GarageArea', 'GarageCond', 'PoolQC']

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,60,0,65.0,8450,0,0,0,0,1,3,...,0,0,0,0,0,0,2,2008,3,0
2,20,0,80.0,9600,0,0,0,0,1,2,...,0,0,0,0,0,0,5,2007,3,0
3,60,0,68.0,11250,0,0,2,0,1,3,...,0,0,0,0,0,0,9,2008,3,0
4,70,0,60.0,9550,0,0,2,0,1,1,...,0,0,0,0,0,0,2,2006,3,5
5,60,0,84.0,14260,0,0,2,0,1,2,...,0,0,0,0,0,0,12,2008,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,60,0,62.0,7917,0,0,0,0,1,3,...,0,0,0,0,0,0,8,2007,3,0
1457,20,0,85.0,13175,0,0,0,0,1,3,...,0,0,0,3,0,0,2,2010,3,0
1458,70,0,66.0,9042,0,0,0,0,1,3,...,0,0,0,4,2,2500,5,2010,3,0
1459,20,0,68.0,9717,0,0,0,0,1,3,...,0,0,0,0,0,0,4,2010,3,0
1460,20,0,75.0,9937,0,0,0,0,1,3,...,0,0,0,0,0,0,6,2008,3,0

In [8]:
x_train = (df_train - df_train.mean())/(df_train.max() - df_train.min())
x_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1,0.018251,-0.135445,-0.017294,-0.009661,-0.00411,-0.045205,-0.251370,-0.06484,0.000685,0.145719,...,-0.006712,-0.031377,-0.003738,-0.141438,-0.019349,-0.002806,-0.392902,0.046062,0.016096,-0.129863
2,-0.217043,-0.135445,0.034075,-0.004285,-0.00411,-0.045205,-0.251370,-0.06484,0.000685,-0.104281,...,-0.006712,-0.031377,-0.003738,-0.141438,-0.019349,-0.002806,-0.120174,-0.203938,0.016096,-0.129863
3,0.018251,-0.135445,-0.007020,0.003427,-0.00411,-0.045205,0.415297,-0.06484,0.000685,0.145719,...,-0.006712,-0.031377,-0.003738,-0.141438,-0.019349,-0.002806,0.243462,0.046062,0.016096,-0.129863
4,0.077075,-0.135445,-0.034418,-0.004519,-0.00411,-0.045205,0.415297,-0.06484,0.000685,-0.354281,...,-0.006712,-0.031377,-0.003738,-0.141438,-0.019349,-0.002806,-0.392902,-0.453938,0.016096,0.870137
5,0.018251,-0.135445,0.047774,0.017496,-0.00411,-0.045205,0.415297,-0.06484,0.000685,-0.104281,...,-0.006712,-0.031377,-0.003738,-0.141438,-0.019349,-0.002806,0.516189,0.046062,0.016096,-0.129863

## loading test data

In [9]:
df_test = pd.read_csv('test_data.csv', index_col='Id')
df_test

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,Inside,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

## preprocess on test data

In [10]:
for col in df_test.columns:
    if col not in ['MSSubClass', 'LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                   '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageYrBlt', 'GarageArea', 'WoodDeckSF', 'EnclosedPorch', 'OpenPorchSF', 'LowQualFinSF',
                  '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'SalePrice', 'MoSold', 'YrSold']:
        tmp = df_test[col].tolist()
        tmp = set(tmp)
        obj1 = enumerate(tmp)
        tmp1 = list(obj1)
        tmp1[0]
        dic = {}
        for i in range(len(tmp1)):
            dic[tmp1[i][1]] = int(tmp1[i][0])
        df_test.replace({col: dic}, inplace=True)
df_test

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,3,80.0,11622,0,0,0,0,1,3,...,120,0,0,3,0,0,6,2010,4,0
1462,20,1,81.0,14267,0,0,2,0,1,1,...,0,0,0,0,2,12500,6,2010,4,0
1463,60,1,74.0,13830,0,0,2,0,1,3,...,0,0,0,3,0,0,3,2010,4,0
1464,60,1,78.0,9978,0,0,2,0,1,3,...,0,0,0,0,0,0,6,2010,4,0
1465,120,1,43.0,5005,0,0,2,1,1,3,...,144,0,0,0,0,0,1,2010,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,4,21.0,1936,0,0,0,0,1,3,...,0,0,0,0,0,0,6,2006,4,0
2916,160,4,21.0,1894,0,0,0,0,1,3,...,0,0,0,0,0,0,4,2006,4,5
2917,20,1,160.0,20000,0,0,0,0,1,3,...,0,0,0,0,0,0,9,2006,4,5
2918,85,1,62.0,10441,0,0,0,0,1,3,...,0,0,0,3,1,700,7,2006,4,0
2919,60,1,74.0,9627,0,0,0,0,1,3,...,0,0,0,0,0,0,11,2006,4,0

## replace NaN with mean of column in test data

In [11]:
null_columns=df_test.columns[df_test.isnull().any()]
print(null_columns)
for i in null_columns:
    print(df_test[df_test[i].isnull()][null_columns])
for i in null_columns:
    df_test[i].fillna((df_test[i].mean()), inplace=True)
null_columns=df_test.columns[df_test.isnull().any()]
print(null_columns)

Index(['LotFrontage', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'GarageYrBlt', 'GarageArea'],
      dtype='object')
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
1467          NaN         0.0       935.0         0.0      233.0       1168.0
1501          NaN      1159.0       466.0         0.0      290.0        756.0
1502          NaN         0.0       244.0         0.0      286.0        530.0
1506          NaN       120.0       506.0         0.0     1323.0       1829.0
1508          NaN         0.0       687.0        46.0      491.0       1224.0
...           ...         ...         ...         ...        ...          ...
2848          NaN         0.0       872.0         0.0      476.0       1348.0
2851          NaN         0.0         0.0         0.0     1065.0       1065.0
2901          NaN         0.0       909.0         0.0      723.0       1632.0
2902          NaN         0.0      1136.0       116.0      129.0       1381.0
2909          NaN         0.0       149.0         0.0     1503.0       1652.0

      GarageYrBlt  GarageArea
Id
1467       1992.0       420.0
1501       2000.0       440.0
1502       2003.0       496.0
1506       1967.0       535.0
1508       1978.0       678.0
...           ...         ...
2848       2002.0       418.0
2851       1997.0       467.0
2901       1958.0       518.0
2902       2000.0       470.0
2909       1970.0       928.0

[227 rows x 8 columns]
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
1692          NaN         NaN       651.0         0.0      219.0        870.0
1707         90.0         NaN         0.0         0.0     1436.0       1436.0
1883         70.0         NaN         0.0         0.0      840.0        840.0
1993          NaN         NaN         0.0         0.0      707.0        707.0
2005         87.0         NaN       666.0         0.0      794.0       1460.0
2042          NaN         NaN         0.0         0.0      952.0        952.0
2312         59.0         NaN         0.0         0.0      768.0        768.0
2326          NaN         NaN         0.0         0.0      384.0        384.0
2341         85.0         NaN         0.0         0.0     1528.0       1528.0
2350        112.0         NaN       745.0         0.0      210.0        955.0
2369         30.0         NaN         0.0         0.0     1550.0       1550.0
2593         68.0         NaN       583.0         0.0      963.0       1546.0
2658        103.0         NaN         0.0         0.0     1209.0       1209.0
2687         49.0         NaN      1562.0         0.0      108.0       1670.0
2863         75.0         NaN       475.0       297.0      142.0        914.0

      GarageYrBlt  GarageArea
Id
1692       2002.0       644.0
1707       2008.0       529.0
1883       2002.0       550.0
1993       2002.0       403.0
2005       2006.0       480.0
2042       2002.0       469.0
2312       2007.0       572.0
2326       2003.0       400.0
2341       2007.0       480.0
2350       2007.0       880.0
2369       2007.0       528.0
2593       2207.0       502.0
2658       2005.0       575.0
2687       2006.0       928.0
2863          NaN         0.0
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
2121         99.0         0.0         NaN         NaN        NaN          NaN

      GarageYrBlt  GarageArea
Id
2121       1946.0       280.0
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
2121         99.0         0.0         NaN         NaN        NaN          NaN

      GarageYrBlt  GarageArea
Id
2121       1946.0       280.0
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
2121         99.0         0.0         NaN         NaN        NaN          NaN

      GarageYrBlt  GarageArea
Id
2121       1946.0       280.0
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
2121         99.0         0.0         NaN         NaN        NaN          NaN

      GarageYrBlt  GarageArea
Id
2121       1946.0       280.0
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
1514         98.0       144.0      1500.0         0.0      228.0       1728.0
1532         56.0         0.0       579.0         0.0      357.0        936.0
1540        100.0         0.0         0.0         0.0      840.0        840.0
1553         60.0         0.0         0.0         0.0      780.0        780.0
1557         60.0         0.0      1026.0         0.0      186.0       1212.0
...           ...         ...         ...         ...        ...          ...
2894         60.0         0.0         0.0         0.0      216.0        216.0
2910         21.0         0.0       522.0         0.0      108.0        630.0
2914         21.0         0.0         0.0         0.0      546.0        546.0
2915         21.0         0.0         0.0         0.0      546.0        546.0
2918         62.0         0.0       337.0         0.0      575.0        912.0

      GarageYrBlt  GarageArea
Id
1514          NaN         0.0
1532          NaN         0.0
1540          NaN         0.0
1553          NaN         0.0
1557          NaN         0.0
...           ...         ...
2894          NaN         0.0
2910          NaN         0.0
2914          NaN         0.0
2915          NaN         0.0
2918          NaN         0.0

[78 rows x 8 columns]
      LotFrontage  MasVnrArea  BsmtFinSF1  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
Id
2577         50.0         0.0       548.0         0.0      311.0        859.0

      GarageYrBlt  GarageArea
Id
2577          NaN         NaN
Index([], dtype='object')

## delete columns with more than 0.75 correlation to reduce number of unnecessary features (same column as train data)

In [12]:
df_test = df_test.drop(df_test[to_drop_train], axis=1)
df_test

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,20,3,80.0,11622,0,0,0,0,1,3,...,0,120,0,3,0,0,6,2010,4,0
1462,20,1,81.0,14267,0,0,2,0,1,1,...,0,0,0,0,2,12500,6,2010,4,0
1463,60,1,74.0,13830,0,0,2,0,1,3,...,0,0,0,3,0,0,3,2010,4,0
1464,60,1,78.0,9978,0,0,2,0,1,3,...,0,0,0,0,0,0,6,2010,4,0
1465,120,1,43.0,5005,0,0,2,1,1,3,...,0,144,0,0,0,0,1,2010,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,160,4,21.0,1936,0,0,0,0,1,3,...,0,0,0,0,0,0,6,2006,4,0
2916,160,4,21.0,1894,0,0,0,0,1,3,...,0,0,0,0,0,0,4,2006,4,5
2917,20,1,160.0,20000,0,0,0,0,1,3,...,0,0,0,0,0,0,9,2006,4,5
2918,85,1,62.0,10441,0,0,0,0,1,3,...,0,0,0,3,1,700,7,2006,4,0
2919,60,1,74.0,9627,0,0,0,0,1,3,...,0,0,0,0,0,0,11,2006,4,0

In [13]:
x_test = (df_test - df_test.mean())/(df_test.max() - df_test.min())
x_test.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,
1461,-0.219873,0.279918,0.063797,0.032702,-0.004112,-0.060658,-0.246516,-0.057117,0.001371,0.13194,...,-0.004984,0.178708,-0.00218,0.601097,-0.013251,-0.003422,-0.009471,0.557574,0.010662,-0.123509
1462,-0.219873,-0.120082,0.069383,0.080679,-0.004112,-0.060658,0.420151,-0.057117,0.001371,-0.36806,...,-0.004984,-0.029626,-0.00218,-0.148903,0.653416,0.731872,-0.009471,0.557574,0.010662,-0.123509
1463,0.015422,-0.120082,0.030277,0.072752,-0.004112,-0.060658,0.420151,-0.057117,0.001371,0.13194,...,-0.004984,-0.029626,-0.00218,0.601097,-0.013251,-0.003422,-0.282198,0.557574,0.010662,-0.123509
1464,0.015422,-0.120082,0.052624,0.002881,-0.004112,-0.060658,0.420151,-0.057117,0.001371,0.13194,...,-0.004984,-0.029626,-0.00218,-0.148903,-0.013251,-0.003422,-0.009471,0.557574,0.010662,-0.123509
1465,0.368363,-0.120082,-0.142907,-0.087324,-0.004112,-0.060658,0.420151,0.276217,0.001371,0.13194,...,-0.004984,0.220374,-0.00218,-0.148903,-0.013251,-0.003422,-0.464016,0.557574,0.010662,-0.123509

In [14]:
print(x_train.shape, x_test.shape)

(1460, 71) (1459, 71)

In [15]:
from sklearn.linear_model import TweedieRegressor
reg = TweedieRegressor(power=2, alpha=0.5, link='log')
reg.fit(x_train, y)

TweedieRegressor(alpha=0.5, link='log', power=2)

## find out how much each attribute is impacting on predicting price

In [16]:
reg.coef_

array([-0.01436259, -0.0484064 ,  0.01476694,  0.00849421, -0.00143807,
       -0.00889514,  0.04342237,  0.00376866,  0.00021368, -0.01397507,
       -0.00944993,  0.01522384,  0.00058539,  0.0004893 , -0.01267249,
       -0.02136256,  0.06402819,  0.00080201,  0.05120947,  0.07850012,
       -0.0454151 ,  0.00322977,  0.0258339 , -0.0029397 ,  0.02739391,
        0.06665019, -0.00458513,  0.07723973,  0.00690676,  0.00548577,
        0.00663057,  0.0090296 ,  0.01909208,  0.01093429,  0.00249616,
        0.01773641,  0.0250192 , -0.00396342,  0.02318596,  0.03539426,
        0.01623127,  0.03494991, -0.00041573,  0.03993151,  0.02488262,
        0.00029706,  0.05326208,  0.03484366,  0.01341057, -0.00463918,
        0.07428673,  0.00473521,  0.05995818,  0.00824804,  0.00568732,
        0.06304015,  0.0141826 ,  0.03123739,  0.02580454,  0.02006893,
       -0.00539433,  0.00162843,  0.00982613,  0.00295011, -0.01534546,
       -0.00368152, -0.00023958,  0.00605727, -0.00634703, -0.01064855,
        0.00541578])

In [22]:
np.argmax(reg.coef_)

19

In [23]:
np.argmin(reg.coef_)

1

In [26]:
x_test.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'MasVnrType', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
       'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'Functional', 'Fireplaces', 'GarageType', 'GarageFinish', 'GarageCars',
       'GarageQual', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'Fence',
       'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition'],
      dtype='object')

In [30]:
att_impact = []
for i in range(len(x_test.columns)):
    att_impact.append((x_test.columns[i], reg.coef_[i]))
att_impact.sort(key = lambda x: x[1])
att_impact

[('MSZoning', -0.04840639705550825),
 ('RoofStyle', -0.04541509556315686),
 ('HouseStyle', -0.02136256207284403),
 ('Fence', -0.015345456890141869),
 ('MSSubClass', -0.014362593639412313),
 ('LotConfig', -0.013975073423884177),
 ('BldgType', -0.012672493629236403),
 ('SaleType', -0.010648545081039048),
 ('LandSlope', -0.009449934377985011),
 ('Alley', -0.00889514453717876),
 ('YrSold', -0.0063470250825917824),
 ('EnclosedPorch', -0.005394327275552655),
 ('KitchenAbvGr', -0.0046391772872993765),
 ('ExterCond', -0.004585130886754258),
 ('Heating', -0.00396341953745575),
 ('MiscFeature', -0.0036815193647308595),
 ('MasVnrType', -0.0029397017190090535),
 ('Street', -0.0014380697630930264),
 ('LowQualFinSF', -0.0004157277387612299),
 ('MiscVal', -0.00023958064201893458),
 ('Utilities', 0.000213680769522647),
 ('BsmtHalfBath', 0.00029705708990809295),
 ('Condition2', 0.0004892995527572806),
 ('Condition1', 0.0005853871037577535),
 ('OverallCond', 0.0008020073217509953),
 ('3SsnPorch', 0.0016284339918581185),
 ('BsmtFinSF2', 0.00249615964047795),
 ('PoolArea', 0.0029501069927768014),
 ('RoofMatl', 0.0032297711103879832),
 ('LandContour', 0.003768664775893176),
 ('Functional', 0.004735213925252389),
 ('SaleCondition', 0.005415777984931216),
 ('BsmtCond', 0.0054857682168361),
 ('GarageFinish', 0.005687320080842801),
 ('MoSold', 0.006057270380464847),
 ('BsmtExposure', 0.006630573416560578),
 ('BsmtQual', 0.006906761175401133),
 ('GarageType', 0.008248044864013555),
 ('LotArea', 0.008494205009922713),
 ('BsmtFinType1', 0.009029596311163526),
 ('ScreenPorch', 0.00982612904390539),
 ('BsmtFinType2', 0.010934287613444255),
 ('BedroomAbvGr', 0.013410566840117854),
 ('GarageQual', 0.014182596889792983),
 ('LotFrontage', 0.01476693576876827),
 ('Neighborhood', 0.015223841120910454),
 ('Electrical', 0.016231271642196145),
 ('BsmtUnfSF', 0.017736411264531748),
 ('BsmtFinSF1', 0.019092082921714097),
 ('OpenPorchSF', 0.02006892543706953),
 ('HeatingQC', 0.023185963179598233),
 ('BsmtFullBath', 0.024882619774523496),
 ('TotalBsmtSF', 0.025019200005591654),
 ('WoodDeckSF', 0.025804541963339173),
 ('Exterior1st', 0.025833904441261938),
 ('MasVnrArea', 0.027393912512260542),
 ('PavedDrive', 0.031237389739613465),
 ('HalfBath', 0.0348436607791822),
 ('2ndFlrSF', 0.03494990592695556),
 ('CentralAir', 0.0353942593311767),
 ('GrLivArea', 0.03993150873079073),
 ('LotShape', 0.04342237285300538),
 ('YearBuilt', 0.05120946807582877),
 ('FullBath', 0.053262082847717045),
 ('Fireplaces', 0.05995818084593829),
 ('GarageCars', 0.06304015206833978),
 ('OverallQual', 0.06402818754119377),
 ('ExterQual', 0.06665019007934887),
 ('KitchenQual', 0.07428673460976642),
 ('Foundation', 0.0772397254220555),
 ('YearRemodAdd', 0.07850011954515314)]

In [17]:
reg.intercept_

12.06321625653298

## MSE for train data

In [31]:
y_train_pred = reg.predict(x_train)
y_train_pred

array([198809.05655494, 159881.80257485, 209803.96885097, ...,
       190310.9228714 , 161028.81278547, 155166.6690612 ])

In [33]:
mse = (np.square(y_train_pred - y)).mean()
mse

3439583575.710468

## getting the prediction for test and making it sutable for Kaggle

In [18]:
y_pred = reg.predict(x_test)

In [19]:
y_pred

array([143590.60756883, 161487.40438018, 191054.74178383, ...,
       167580.71352841, 164359.33165165, 198838.80076489])

In [36]:
len(y_pred)

1459

In [56]:
output = pd.DataFrame(columns=['Id', 'SalePrice'])
output

Empty DataFrame
Columns: [Id, SalePrice]
Index: []

In [57]:
for i in range(1461, 2920):
    output = output.append({'Id':i, 'SalePrice':y_pred[i-1461]}, ignore_index=True)
output.Id = output.Id.astype(int)
output = output.set_index('Id')
output

          SalePrice
Id
1461  143590.607569
1462  161487.404380
1463  191054.741784
1464  194318.268072
1465  184272.103456
...             ...
2915  143873.229532
2916  148907.823904
2917  167580.713528
2918  164359.331652
2919  198838.800765

[1459 rows x 1 columns]